package com.example.sentinal_idempotancy_engine.service;

import com.example.sentinal_idempotancy_engine.client.CarbonCalculatorClient;
import com.example.sentinal_idempotancy_engine.dto.CarbonResponse;
import com.example.sentinal_idempotancy_engine.dto.TransactionRequest;
import com.example.sentinal_idempotancy_engine.model.Transaction;
import com.example.sentinal_idempotancy_engine.repository.TransactionRepository;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Slf4j
@Service
public class GreenPayService {

    @Autowired
    private CarbonCalculatorClient carbonClient;

    @Autowired
    private TransactionRepository transactionRepository;

    /**
     * Processes the sustainability logic for a transaction.
     * @param request The incoming payment request
     * @param internalTxId The ID generated by our system
     */
    @Transactional
    public void calculateAndSaveImpact(TransactionRequest request, String internalTxId) {
        
        // 1. Create the Transaction Entity
        Transaction transaction = new Transaction();
        transaction.setTransactionId(internalTxId);
        transaction.setAmount(request.getAmount());
        transaction.setCurrency(request.getCurrency());
        transaction.setMcc(request.getMcc());

        try {
            // 2. [FEIGN] Call external API to get CO2 data for this Merchant Category (MCC)
            log.info("GreenPay: Fetching carbon impact for MCC: {}", request.getMcc());
            CarbonResponse impact = carbonClient.getCarbonImpact(request.getMcc());

            // 3. Calculate total footprint: (Amount * Grams Per Dollar)
            double totalCo2 = request.getAmount() * impact.getCo2GramsPerDollar();
            
            transaction.setCo2Grams(totalCo2);
            transaction.setSustainabilityCategory(impact.getCategory());
            
            log.info("GreenPay: Calculation successful. Impact: {}g CO2", totalCo2);

        } catch (Exception e) {
            // 4. [RESILIENCE] Fallback if the external API fails
            log.error("GreenPay: Carbon API unavailable. Saving transaction with default values. Error: {}", e.getMessage());
            transaction.setCo2Grams(0.0);
            transaction.setSustainabilityCategory("DATA_UNAVAILABLE");
        }

        // 5. Save to PostgreSQL
        transactionRepository.save(transaction);
    }
}