package com.example.sentinal_idempotancy_engine.repository;

import com.example.sentinal_idempotancy_engine.model.Transaction;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * Repository for managing Transaction entities in PostgreSQL.
 * Extending JpaRepository provides standard Save, Delete, and Find methods.
 */
@Repository
public interface TransactionRepository extends JpaRepository<Transaction, Long> {

    /**
     * Finds a transaction by the unique ID generated by our system.
     * Use case: When a customer wants to see the carbon footprint of a specific past purchase.
     */
    Optional<Transaction> findByTransactionId(String transactionId);

    /**
     * Optional: You could add a method here to find all transactions for a specific MCC.
     * This would be useful for "Sustainability Analytics" reports.
     */
}